services:
  - type: web
    name: rails-app
    env: ruby
    buildCommand: "bundle install && bundle exec rake assets:precompile db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: rails-db

